name: Full tests

on:
  schedule:
    - cron:  '00 19 * * *'

jobs:
  unit-test:
    name: Full tests for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Configure pagefile
        if: runner.os == 'Windows'
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 6GB
      - name: Set up swap space
        if: runner.os == 'Linux'
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 6
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
      - name: Install PyTorch
        run: |
         if [ "$RUNNER_OS" == "macOS" ]; then
              conda install pytorch torchvision -c pytorch
         else
              conda install pytorch torchvision cpuonly -c pytorch
         fi
      - name: Install TinyNeuralNetwork
        run: python setup.py install
      - name: Install test dependencies
        run: pip install flake8 tensorflow pytest interval
      - name: Lint checks
        run: python -m flake8
      - name: Run tests
        run: |
          source activate.sh
          pytest tests -v
